name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      run: terraform init

    - name: Force Remove State
      run: |
        rm -f terraform.tfstate*
        rm -rf .terraform*
        terraform init

    - name: Check for existing instances
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=github-tests" --query "Reservations[].Instances[?State.Name=='running'].InstanceId" --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        if [ ! -z "$INSTANCE_ID" ]; then
          echo "Found instance: $INSTANCE_ID"
        fi

    - name: Force Terminate Instance
      if: env.INSTANCE_ID != ''
      run: |
        echo "Terminating instance ${{ env.INSTANCE_ID }}"
        aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
        
        # Wait for termination to complete
        echo "Waiting for instance to terminate..."
        aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}

    - name: Final Verification
      run: |
        echo "Performing final verification..."
        sleep 10  # Give AWS some time to update instance states
        REMAINING=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=github-tests" "Name=instance-state-name,Values=running,pending" --query "Reservations[].Instances[].InstanceId" --output text)
        if [ ! -z "$REMAINING" ]; then
          echo "Error: Instances still exist: $REMAINING"
          exit 1
        else
          echo "All instances successfully terminated"
        fi