name: "Terraform Destroy"

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve